name: scp test ubuntu

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:           
  containertest:
    runs-on: ubuntu-latest
    container:
      image: mm0820/ant_test:0.1
    steps: 
    - name: test
      run: |
        echo $JAVA_HOME
    - uses: actions/checkout@v3
    - name: test2
      run: |
        ls -al
  scp:
    name: scp
    runs-on: ubuntu-latest
    container:
      image: mm0820/sshpass:0.1
    env:
        TEST: ${{ secrets.PASSWORD4 }}
        CHECK: ${{ secrets.NOCH }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
    steps:
    - uses: actions/checkout@v3
      name: Run a multi-line script
    - name: secrets test
      run: |
        #bash ssh.sh
        sshpass -p $TEST ssh $CHECK $USERNAME@$HOST dir
        sshpass -p $TEST scp README.md $USERNAME@HOST:c:/
      
